cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(regdrive C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(regdrive regdrive.c)
pico_enable_stdio_usb(regdrive 1)
pico_enable_stdio_uart(regdrive 0)
target_link_libraries(regdrive pico_stdlib)
pico_add_extra_outputs(regdrive)
