cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(xorled C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(xorled xorled.c)
target_include_directories(xorled PRIVATE ${CMAKE_CURRENT_LIST_DIR})
pico_enable_stdio_usb(xorled 1)
pico_enable_stdio_uart(xorled 0)
target_link_libraries(xorled pico_stdlib)
pico_add_extra_outputs(xorled)

add_executable(ternary ternary.c)
pico_enable_stdio_usb(ternary 1)
pico_enable_stdio_uart(ternary 0)
target_link_libraries(ternary pico_stdlib)
pico_add_extra_outputs(ternary)
