cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(rawbyte C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(rawbyte rawbyte.c)
pico_enable_stdio_usb(rawbyte 1)
pico_enable_stdio_uart(rawbyte 0)
target_link_libraries(rawbyte pico_stdlib)
pico_add_extra_outputs(rawbyte)
