cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(trainedled C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(trainedled trainedled.c)
pico_enable_stdio_usb(trainedled 1)
pico_enable_stdio_uart(trainedled 0)
target_link_libraries(trainedled pico_stdlib)
pico_add_extra_outputs(trainedled)
