cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(setuplearn C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(setuplearn setuplearn.c)
pico_enable_stdio_usb(setuplearn 1)
pico_enable_stdio_uart(setuplearn 0)
target_link_libraries(setuplearn pico_stdlib)
pico_add_extra_outputs(setuplearn)
